# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/db/schema.rs"
with_docs = true
import_types = ["diesel::sql_types::*", "crate::db::enums::*"]
patch_file = "src/db/schema.patch"
